// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfBwq-BjehTHiu-AyCHNPDYOwGwL0YNJI',
    appId: '1:196853510035:web:23bc1e74f1707d5ddb4266',
    messagingSenderId: '196853510035',
    projectId: 'makkah-journey-4eead',
    authDomain: 'makkah-journey-4eead.firebaseapp.com',
    storageBucket: 'makkah-journey-4eead.firebasestorage.app',
    measurementId: 'G-KQMM71WR4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWtkTiwP6rFSlSOX6djF-hqMajHhijKuI',
    appId: '1:196853510035:android:a6fedf3ae2189891db4266',
    messagingSenderId: '196853510035',
    projectId: 'makkah-journey-4eead',
    storageBucket: 'makkah-journey-4eead.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeOCYUEHTMv71fh31EjGOn-u2JE7x04Qk',
    appId: '1:196853510035:ios:6850807817d9dd9edb4266',
    messagingSenderId: '196853510035',
    projectId: 'makkah-journey-4eead',
    storageBucket: 'makkah-journey-4eead.firebasestorage.app',
    iosBundleId: 'com.example.makkahjourney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeOCYUEHTMv71fh31EjGOn-u2JE7x04Qk',
    appId: '1:196853510035:ios:6850807817d9dd9edb4266',
    messagingSenderId: '196853510035',
    projectId: 'makkah-journey-4eead',
    storageBucket: 'makkah-journey-4eead.firebasestorage.app',
    iosBundleId: 'com.example.makkahjourney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfBwq-BjehTHiu-AyCHNPDYOwGwL0YNJI',
    appId: '1:196853510035:web:27b06fa74fd98beddb4266',
    messagingSenderId: '196853510035',
    projectId: 'makkah-journey-4eead',
    authDomain: 'makkah-journey-4eead.firebaseapp.com',
    storageBucket: 'makkah-journey-4eead.firebasestorage.app',
    measurementId: 'G-H384J1FGXG',
  );
}
